java_library(
    name = "driver",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//java/me/blexim/proptest/common",
        "//java/me/blexim/proptest/minimise",
        "//java/me/blexim/proptest/runner",
        "//third_party/guava",
        "//third_party/slf4j",
    ],
)
