java_library(
    name = "driver",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
      "//java/me/blexim/proptest/common",
      "//third_party/slf4j",
      "@auto_value//jar",
      "@guava//jar",
    ],
)
