java_library(
    name = "multiset",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//examples/multiset/proto/me/blexim/multiset:multiset_proto_java",
        "//third_party/guava",
        "//third_party/protobuf",
        "//third_party/slf4j",
    ],
)
