java_test(
    name = "test",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    size = "small",
    deps = [
      "//java/me/blexim/proptest/common",
      "//third_party/auto_value",
      "//third_party/guava",
      "//third_party/slf4j",
      "//third_party/testing",
    ],
)
