java_test(
    name = "test",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    test_class = "me.blexim.proptest.common.InputSequenceTest",
    size = "small",
    deps = [
      "//java/me/blexim/proptest/common",
      "//third_party/auto_value",
      "//third_party/slf4j",
      "//third_party/testing",
      "@guava//jar",
    ],
)
