java_library(
    name = "generator",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//java/me/blexim/proptest/common",
        "//third_party/guava",
        "//third_party/protobuf",
        "//third_party/slf4j",
    ],
)
