java_library(
    name = "generator",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
      "//java/me/blexim/proptest/common",
      "//third_party/guava",
      "//third_party/protobuf",
      "//third_party/slf4j",
    ],
)
