java_library(
    name = "distributed",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
      "//java/me/blexim/proptest/common",
      "//third_party/auto_value",
      "//third_party/guava",
      "//third_party/slf4j",
    ],
)
