java_library(
    name = "runner",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//java/me/blexim/proptest/common",
        "//java/me/blexim/proptest/generator",
        "//third_party/auto_value",
        "//third_party/guava",
    ],
)
