java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//examples/multiset/java/me/blexim/multiset",
        "//examples/multiset/proto/me/blexim/multiset:multiset_proto_java",
        "//third_party/slf4j",
    ],
)
