java_proto_library(
    name = "multiset_proto_java",
    visibility = ["//visibility:public"],
    deps = [
        ":multiset_proto",
    ],
)

proto_library(
    name = "multiset_proto",
    srcs = glob(["*.proto"]),
)
