

java_proto_library(
  name = "proptest_proto_java",
  visibility = ["//visibility:public"],
  deps = [
    ":proptest_proto",
  ],
)

proto_library(
    name = "proptest_proto",
    srcs = glob(["*.proto"]),
)