java_test(
    name = "test",
    size = "small",
    srcs = glob(["*.java"]),
    test_class = "me.blexim.proptest.minimise.DeltaDebuggingMinimiserTest",
    visibility = ["//visibility:public"],
    deps = [
        "//java/me/blexim/proptest/common",
        "//java/me/blexim/proptest/minimise",
        "//third_party/guava",
        "//third_party/slf4j",
        "//third_party/testing",
    ],
)
